# Generated by Django 4.0.3 on 2022-04-01 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa')),
                ('description', models.TextField(verbose_name='Opis')),
                ('type', models.CharField(choices=[('foundation', 'fundacja'), ('non-governmental organization', ' organizacja pozarządowa'), ('local collection', 'zbiórka lokalna')], default='foundation', max_length=32)),
                ('categories', models.ManyToManyField(to='main_app.category', verbose_name='Kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Liczba worków')),
                ('address', models.CharField(max_length=128, verbose_name='Adres')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Numer telefonu')),
                ('city', models.CharField(max_length=32, verbose_name='Miasto')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('pick_up_date', models.DateField(verbose_name='Data odebrania')),
                ('pick_up_time', models.TimeField(verbose_name='Godzina odebrania')),
                ('pick_up_comment', models.TextField(verbose_name='Komentarz do przesyłki')),
                ('categories', models.ManyToManyField(to='main_app.category', verbose_name='Kategorie')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.institution', verbose_name='Instytucja')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
